/**
 * LabStock プライバシーポリシー
 * アプリ内表示用のテキストデータ
 */

export const PRIVACY_POLICY_JA = `
# プライバシーポリシー

最終更新日: 2026年6月28日

本プライバシーポリシー（以下「本ポリシー」）は、LabStock（以下「本アプリ」）における個人情報およびユーザー情報の取り扱いについて定めるものです。本アプリをご利用いただく前に、本ポリシーをよくお読みください。

## 1. 運営者情報

本アプリは、個人開発者（以下「運営者」）が提供するモバイルアプリケーションです。お問い合わせは、App Store の本アプリ製品ページに記載のサポート連絡先までお願いいたします。

## 2. 収集する情報と保存場所

### 2.1 端末内にのみ保存される情報

通常の在庫管理でユーザーが入力する以下の情報は、ユーザーの端末内（ローカルストレージ）にのみ保存され、外部には送信されません。

- **ユーザー名**: アプリ内での表示名として使用
- **在庫データ**: 物品名、企業名、型番、個数、カテゴリ、画像、バーコード情報
- **変更ログ**: 在庫数の変更履歴（変更者名、日時、変更内容）
- **アラート設定**: 在庫不足の閾値設定

### 2.2 グループ共有機能を利用する場合にクラウドへ保存される情報

ユーザーが任意で「グループ共有」機能を利用した場合に限り、グループのメンバー間で在庫を共有する目的で、以下の情報がクラウドのデータベース（後述の Supabase）に保存されます。

- **グループ情報**: グループ名、説明、招待コード
- **共有在庫データ**: グループ内で登録した物品名・個数・保管場所・カテゴリ等
- **表示名と活動ログ**: 操作したメンバーの表示名、操作内容、日時
- **端末識別子**: ログインの代わりにメンバーを識別するために本アプリが生成するランダムなID（氏名・メールアドレス等の個人を特定する情報は含みません）

グループ共有機能を利用しない場合、これらの情報がクラウドへ送信されることはありません。

### 2.3 広告のために自動的に収集される情報

本アプリは広告配信に Google AdMob を利用しており、広告配信のため以下の情報が AdMob により収集される場合があります。

- **デバイス情報**: 端末の種類、OSバージョン、言語設定等
- **利用状況データ**: 広告の表示回数等

本アプリは**非パーソナライズ広告**として広告を配信しており、**広告識別子（IDFA）を用いた行動トラッキングは行いません**。そのため、App Tracking Transparency（ATT）の許可ダイアログは表示されません。

### 2.4 カメラ・写真ライブラリへのアクセス

本アプリは、物品の画像撮影・添付、およびバーコード/QRコードの読み取りのために、カメラおよび写真ライブラリへのアクセスを要求する場合があります。これらの機能は、ユーザーが明示的に許可した場合にのみ利用されます。個人の在庫に添付した画像は端末内にのみ保存されます。

## 3. 情報の利用目的

| 情報の種類 | 利用目的 |
|---|---|
| ユーザー名・表示名 | 変更ログ・活動ログの記録および表示 |
| 在庫データ | 在庫管理機能の提供 |
| グループ・共有在庫・活動ログ | グループメンバー間での在庫共有機能の提供 |
| 端末識別子 | グループ内でのメンバー識別（ログインを不要にするため） |
| アラート設定 | 在庫不足通知の送信 |
| デバイス・利用状況情報 | 広告（非パーソナライズ）の配信 |

## 4. 情報の保存場所とセキュリティ

### 4.1 保存場所

- 個人の在庫データ・ユーザー名・各種設定は、ユーザーの端末内（ローカルストレージ）にのみ保存されます。
- グループ共有機能で共有された在庫データは、共有を実現するため、クラウドのデータベース（Supabase Inc. が提供するホスティング／データベースサービス）に保存されます。

### 4.2 セキュリティ対策

- クラウドに保存されるグループデータは、アクセス制御により、当該グループに参加しているメンバーのみが閲覧・編集できるよう保護されています。
- 通信は暗号化（HTTPS）されています。
- 入力データのバリデーションおよびサニタイズ処理を行っています。

## 5. 第三者サービス・情報提供

本アプリは以下の第三者サービスを利用します。

- **Google AdMob**（広告配信）: 広告配信の最適化のために端末情報や利用状況を収集する場合があります。プライバシーポリシー: https://policies.google.com/privacy
- **Supabase**（グループ共有機能のデータベース・ホスティング）: グループ共有機能を利用した場合の共有データの保存先です。プライバシーポリシー: https://supabase.com/privacy

上記を除き、ユーザーの情報を第三者に提供することはありません。ただし、ユーザーの同意がある場合、法令に基づく開示請求があった場合、または人の生命・身体・財産の保護のために必要がある場合を除きます。

## 6. ユーザーの権利

### 6.1 データの確認・修正

ユーザーは、アプリ内の各画面から、保存されている在庫データや設定情報をいつでも確認・修正できます。

### 6.2 データの削除

- 設定画面の「全データ削除」機能により、端末内に保存されているすべてのデータを完全に削除できます。また、アプリをアンインストールすることで、端末内のすべてのデータが削除されます。
- グループ共有データについては、グループから退出するとご自身のアクセスがなくなり、グループの作成者がグループを削除すると、そのグループの共有データはクラウドから完全に削除されます。

## 7. 児童のプライバシー

本アプリは、13歳未満の児童を対象としたサービスではありません。13歳未満の児童から意図的に個人情報を収集することはありません。

## 8. 本ポリシーの変更

運営者は、必要に応じて本ポリシーを変更することがあります。重要な変更がある場合は、アプリ内の通知またはアプリのアップデート情報にてお知らせします。変更後のポリシーは、アプリ内に掲載された時点から効力を生じるものとします。

## 9. 準拠法

本ポリシーは、日本法に準拠し、解釈されるものとします。

## 10. お問い合わせ

本ポリシーに関するお問い合わせは、App Store の本アプリ製品ページに記載のサポート連絡先までお願いいたします。
`;

export const PRIVACY_POLICY_EN = `
# Privacy Policy

Last updated: June 28, 2026

This Privacy Policy ("Policy") describes how LabStock ("the App") handles personal information and user data. Please read this Policy carefully before using the App.

## 1. Information We Collect and Where It Is Stored

### 1.1 Stored only on your device

The following information you enter for ordinary inventory management is stored only in your device's local storage and is not transmitted externally:

- **Username**: Display name within the app
- **Inventory data**: Item names, company names, model numbers, quantities, categories, images, barcode information
- **Change logs**: Inventory change history (who changed, when, what)
- **Alert settings**: Low-stock threshold configurations

### 1.2 Stored in the cloud only when you use Group Sharing

Only when you choose to use the optional "Group Sharing" feature, the following is stored in a cloud database (Supabase, see below) so that members of a group can share an inventory:

- **Group information**: Group name, description, invite code
- **Shared inventory data**: Item names, quantities, locations, categories, etc. registered within the group
- **Display names and activity logs**: The display name of the member who performed an action, the action, and the time
- **Device identifier**: A random ID generated by the App to identify members instead of requiring a login (it contains no personally identifying information such as name or email)

If you do not use Group Sharing, none of this information is sent to the cloud.

### 1.3 Information collected automatically for advertising

The App uses Google AdMob for advertising. AdMob may collect device information (device type, OS version, language) and usage data (such as ad impressions). The App serves **non-personalized ads only and does NOT perform IDFA-based tracking**, so no App Tracking Transparency (ATT) prompt is shown.

### 1.4 Camera and Photo Library Access

The App may request access to your camera and photo library to take/attach item photos and to scan barcodes/QR codes. These are used only with your explicit permission. Images attached to personal inventory are stored only on your device.

## 2. How We Use Your Information

| Information | Purpose |
|---|---|
| Username / display name | Recording and displaying change/activity logs |
| Inventory data | Providing inventory management features |
| Group / shared inventory / activity logs | Providing inventory sharing among group members |
| Device identifier | Identifying members within a group (to avoid requiring login) |
| Alert settings | Sending low-stock notifications |
| Device / usage data | Delivering (non-personalized) advertising |

## 3. Data Storage and Security

- Personal inventory data, username, and settings are stored only on your device.
- Inventory shared via Group Sharing is stored in a cloud database provided by Supabase Inc. to enable sharing. Cloud-stored group data is access-controlled so that only members of that group can view or edit it. Communication is encrypted (HTTPS).

## 4. Third-Party Services

- **Google AdMob** (advertising): https://policies.google.com/privacy
- **Supabase** (database/hosting for Group Sharing): https://supabase.com/privacy

Except as above, we do not provide your information to third parties, other than with your consent, as required by law, or to protect life, body, or property.

## 5. Your Rights

- **Access and modify**: View and edit your data anytime within the app.
- **Delete**: Use "Delete All Data" in Settings to permanently remove all on-device data. Leaving a group removes your access; when a group's creator deletes the group, its shared data is permanently removed from the cloud.

## 6. Children's Privacy

The App is not intended for children under 13. We do not knowingly collect personal information from children under 13.

## 7. Changes to This Policy

We may update this Policy as needed. Significant changes will be communicated through app notifications or update notes.

## 8. Contact

For questions about this Policy, please contact us via the support contact listed on the App's App Store product page.
`;
